### ISSUE TITLE
add instructions on how to compile the project on linux

### ISSUE THREAD

**Issue by 1player** [SlyFabi/VfioUsbManager#1]
I'm trying to create a PKGBUILD for this project, to post on AUR, but I have no idea how to compile it on Linux. Might be a good idea to add instructions on the README.

**Comment by SlyFabi** [comment]
Instructions added.

**Comment by SlyFabi** [comment]
Sorry, I was a bit too fast here, there a 2 dependencies which are not in the repo, I will add instructions to build them as well.

**Comment by SlyFabi** [comment]
I´ve included a build script which downloads and build the required dependencies automatially.
